openapi: 3.0.0
info:
  title: Video Interview API
  version: "1.0"
  description: API for managing video interviews and invitations.
servers:
  - url: 'https://api.example.com/'

paths:
  /interviews:
    get:
      summary: List all interviews
      operationId: listInterviews
      responses:
        '200':
          description: A list of video interviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VideoInterview'

  /interviews/{interviewId}:
    get:
      summary: Get details of a specific interview
      operationId: getInterview
      parameters:
        - name: interviewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Interview details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoInterviewDetails'

  /interviews/invitation:
    post:
      summary: Create an interview invitation
      operationId: createInterviewInvitation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInterviewInvitationParams'
      responses:
        '201':
          description: Invitation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateInterviewInvitationResponse'

  /interviews/{interviewId}/responses/{responseId}:
    get:
      summary: Retrieve a specific interview response
      operationId: getInterviewResponse
      parameters:
        - name: interviewId
          in: path
          required: true
          schema:
            type: string
        - name: responseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Interview response details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetInterviewResponseResponse'

components:
  schemas:
    Candidate:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string

    VideoInterview:
      type: object
      properties:
        id:
          type: string
        label:
          type: string

    VideoInterviewDetails:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    CreateInterviewInvitationParams:
      type: object
      properties:
        interview_id:
          type: string
        candidate:
          $ref: '#/components/schemas/Candidate'

    CreateInterviewInvitationResponse:
      type: object
      properties:
        id:
          type: string

    GetInterviewResponseResponse:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum: [pending, completed]
        report_url:
          type: string
          nullable: true
        public_report_url:
          type: string
          nullable: true
        details:
          type: object
          additionalProperties: true
